/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 1340e8c80b729f82d278075e6bfb425a)
interface __BaseEnv_Env {
	PINTEREST_SESSIONS: KVNamespace;
	EXPO_PUBLIC_YOUCAM_FUNCTION_URL: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./cloudflare/worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "EXPO_PUBLIC_YOUCAM_FUNCTION_URL">> {}
}
